### ISSUE TITLE
Release of v4 (roadmap)

### ISSUE THREAD

**Issue by d8vjork** [skore/laravel-json-api#1]
- [ ] Remove all the authorisation logic (policies)
- [ ] Add built-in query builder
- [ ] Add unified helper (global function + facade)
- [ ] Refactor all the parsing to a more generic code (adding the method `Model::toJsonApi()`)
- [ ] Add error formatting (to handler, maybe creating an additional, non required, setup step): https://jsonapi.org/format/#errors

**Comment by d8vjork** [comment]
Closing this in favour of https://github.com/open-southeners/laravel-apiable
